Product apples = new Product("Apples", 001, 1.07, 5);
Product Cuties = new Product("Cuties", 021, 5.06, 1);
Product Bananas = new Product("Bananas", 002, 0.57, 4);
Product Grapes = new Product("Grapes", 034, 6.01, 1);
Customer John = new Customer("John Doe", new Address("534 Wallaby Dr.","Memphis","TN",12034,"USA"));
Order One = new Order(new List<Product>{apples,Cuties,Bananas,Grapes}, John);
One.getPackingLabel();
Console.WriteLine($"Your total cost is: ${One.getPriceTotal()}");
One.getShippingLabel();
Console.WriteLine("---------------------------------------");
Customer Jacob = new Customer("Jacob Doe", new Address("534 Sydney Dr.","Dublin","Leinster",24,"IE"));
Order Two = new Order(new List<Product>{apples,Cuties,Bananas}, Jacob);
Two.getPackingLabel();
Console.WriteLine($"Your total cost is: ${Two.getPriceTotal()}");
Two.getShippingLabel();
Console.WriteLine("---------------------------------------");
Customer Jingleheimer = new Customer("Jingleheimer Doe", new Address("1234 Sesame St.","Elmo","RD",12345,"USA"));
Order Three = new Order(new List<Product>{apples,Bananas,Grapes}, Jingleheimer);
Three.getPackingLabel();
Console.WriteLine($"Your total cost is: ${Three.getPriceTotal()}");
Three.getShippingLabel();